### ISSUE TITLE
Create the App

### ISSUE THREAD

**Issue by denispasin** [THP-2-0/THP2_back#1]
### Must have:
- [ ] Postgresql
- [ ] No front
- [ ] No Tests framework

### Todo
- [ ] Read through the `rails new --help` documentation
- [ ] Create the app
