### ISSUE TITLE
Configure Coverage

### ISSUE THREAD

**Issue by denispasin** [THP-2-0/THP2_back#25]
## Why ?

Sometimes we think that we have enough tests, sometimes we don't. How about having a metric that will give us a better vision ? 

For this, there's coverage. It helps us to know what have been tested and what haven't. However, we can still write stupid tests without any expect that cover all the lines. 

Consider it as a maximum of trust you can have in a codebase.

## Must have

* [ ] Coverage on test run if `COVERAGE` env var is set
* [ ] Tests must fail with low coverage
* [ ] husky run coverage 

## Todo

* [ ] Add [https://github.com/colszowka/simplecov](simplecov)
* [ ] Add the coverage directory to gitignore
* [ ] Configure simplecov to run with rspec
* Configure it to:
  * [ ] Fail if there's less than 95% of code coverage on the app
  * [ ] Fail if there's less than 90% of code coverage on a single file
  * [ ] Not watch files with less than 5 lines
  * [ ] Separate files with a rails template + a tab for serializers

## Reading list
* https://github.com/colszowka/simplecov#configuring-simplecov
* https://github.com/colszowka/simplecov#want-to-use-bootsnap-with-simplecov
