### ISSUE TITLE
Add policies

### ISSUE THREAD

**Issue by denispasin** [THP-2-0/THP2_back#29]
## Why ?

Because everyone isn't authorized to do everything.

## Must have

- [ ] Proper policies in place
- [ ] The API must nicely answer with `401` when unauthorized

## Todo

- [ ] Add [https://github.com/varvet/pundit](pundit) gem
- [ ] Write a policy so that only its creator can modify or delete a lesson
- [ ] Test it :D
